name: CD - Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # مهم جدًا

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Minikube Docker Env
        run: eval $(minikube docker-env)

      - name: Build Docker Image
        run: docker build -t mysakn-app:1 .

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f k8s/
